

name: Build and Deploy QuickFIX

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.12']

    steps:
      - name: Checkout QuickFIX master branch
        uses: actions/checkout@v4
        with:
          repository: quickfix/quickfix
          ref: master

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Setup MSVC
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel cibuildwheel

      - name: Ensure Visual Studio 2019 is installed
        run: |
          choco install visualstudio2019buildtools --package-parameters "--add Microsoft.VisualStudio.Workload.VCTools --includeRecommended --includeOptional"
          choco install vswhere

      - name: Locate Visual Studio 2019
        id: locate-vs
        run: |
          vswhere -latest -products * -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -property installationPath

      - name: Configure QuickFIX
        run: |
          cd src
          echo '#define HAVE_STLPORT 1' >> config_windows.h
          echo '#define HAVE_ODBC 1' >> config_windows.h
          echo '#define HAVE_MYSQL 1' >> config_windows.h
          echo '#define HAVE_POSTGRESQL 1' >> config_windows.h

      - name: Build QuickFIX
        run: |
          set PATH=%PATH%;${{ steps.locate-vs.outputs.installationPath }}\MSBuild\Current\Bin
          mkdir build
          cd build
          cmake -G "Visual Studio 16 2019" -A x64 -DHAVE_SSL=ON -DCMAKE_INSTALL_PREFIX="C:/quickfix" ..
          cmake --build . --config Release
          cmake --install .

      - name: Build wheel
        env:
          CIBW_BUILD: cp312-win_amd64
          CIBW_BEFORE_BUILD: pip install cmake
        run: python -m cibuildwheel --output-dir wheelhouse

      - uses: actions/upload-artifact@v4
        with:
          name: quickfix-wheels
          path: ./wheelhouse/*.whl

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: quickfix-wheels
          path: dist
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
