name: Build and Deploy

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: [ '3.12' ]
        os: [ 'ubuntu-latest' ]

    steps:
      - uses: actions/checkout@v4

      - name: Setup
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential autoconf automake libtool pkg-config openssl libssl-dev dos2unix libltdl-dev
          sudo apt-get install -y mysql-server mysql-client libmysqlclient-dev
          sudo apt-get install -y postgresql postgresql-contrib libpq-dev wget
          sudo apt-get install -y docker.io

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: pip install setuptools wheel auditwheel

      - name: Convert line endings
        run: dos2unix ./build.sh

      - name: Make build.sh executable
        run: chmod +x ./build.sh

      - name: Build
        env:
          CPLUS_INCLUDE_PATH: /usr/include/mysql:/usr/include/postgresql
        run: |
          CXXFLAGS="-Wno-stringop-truncation"
          ./build.sh

      - name: Fix Linux wheel
        run: |
          docker run --rm -v $(pwd):/io quay.io/pypa/manylinux2014_x86_64 /bin/bash -c "
            auditwheel repair /io/dist/*.whl --plat manylinux_2_17_x86_64 -w /io/wheelhouse/
          "

      - name: Upload wheel to artifact
        uses: actions/upload-artifact@v3
        with:
          name: built-wheel
          path: wheelhouse/*.whl

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download built wheel
        uses: actions/download-artifact@v3
        with:
          name: built-wheel
          path: ./dist

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          github_token: ${{ secrets.GH_PAT }}
          publish_dir: ./dist
